export enum Role {
  ADMIN = 'ADMIN',
  USER = 'USER',
  GUEST = 'CLIENT',
  MODERATOR = 'MODERATOR',
  BORRORWER = 'BORRORWER',
  LENDER = 'LENDER',
  SUPPORT = 'SUPPORT',
  SUPERADMIN = 'SUPERADMIN',
  MANAGER = 'MANAGER',
}
